
ignore: []
# 忽略的文件
ignoresPatterns: [
  "build",
  "dist"
]

#.depcheckrc.yml 文件是用于配置 depcheck 工具的配置文件。depcheck 是一个用于检查项目中未使用的依赖项（无用依赖）的工具。它可以帮助您找出项目中没有被代码直接引用的依赖包，从而进行清理和优化。
#
#该工具的配置文件 .depcheckrc.yml 允许您定义一些选项和规则，以控制 depcheck 在检查项目时的行为和输出。
#
#以下是一些可能在 .depcheckrc.yml 文件中配置的选项：
#
#ignore：指定要忽略的文件、目录和依赖项。您可以在此处列出不需要被 depcheck 检查的部分。
#
#skip-missing：跳过检查缺少的依赖项。如果项目中的某个依赖项没有在 package.json 中定义，但是您确定它是有效的，您可以通过这个选项跳过对它的检查。
#
#ignores：用于定义忽略检查的特定文件或依赖项。与 ignore 类似，但是可以在这里指定更具体的文件或依赖项。
#
#detectors：自定义依赖项检测器。您可以指定自定义的检测规则，以适应特定项目的需求。
#
#specials：定义特殊的依赖项检测规则。例如，您可以定义针对某种特定类型的依赖项的检测规则。
#
#parsers：指定用于解析不同类型文件的解析器。这可以帮助 depcheck 更好地分析项目中的依赖项。
#
#通过配置 .depcheckrc.yml 文件，您可以根据项目的特定需求来自定义 depcheck 的行为，从而更有效地找出项目中的无用依赖并进行优化。
