packages:
  - "packages-vue/vue-hooks"
  - "packages-react"
  - "packages-eslint-conf"
  - "packages-stylelint-conf"
  - "packages-style"
  - "packages-utils"
  - "packages-rc"
  - "packages-conf"
  - "packages-enum"
  - "packages-types"