packages:
  - packages*/**
catalog:
  "@commitlint/cli": ^19.6.1
  "@commitlint/config-conventional": ^19.6.0
  commitlint-plugin-function-rules: ^4.0.1
  depcheck: ^1.4.7
  husky: ^9.1.7
  lerna: ^8.1.9
  lint-staged: ^15.3.0
  markdownlint-cli2: ^0.17.1
  npm-package-json-lint-config-default: ^7.0.1
