packages:
  - packages*/**
  - envs
catalog:
  "@ant-design/v5-patch-for-react-19": ^1.0.3
  "@changesets/cli": ^2.29.5
  "@chromatic-com/storybook": ^3.2.7
  "@clack/prompts": ^0.11.0
  "@commitlint/cli": ^19.8.0
  "@commitlint/config-conventional": ^19.8.0
  "@emotion/css": ^11.13.5
  "@eslint/js": ^9.24.0
  "@faker-js/faker": ^9.7.0
  "@manypkg/get-packages": ^3.1.0
  "@storybook/addon-essentials": ^8.6.14
  "@storybook/addon-interactions": ^8.6.12
  "@storybook/addon-onboarding": ^8.6.12
  "@storybook/blocks": ^8.6.14
  "@storybook/experimental-addon-test": ^8.6.14
  "@storybook/react": ^8.6.12
  "@storybook/react-vite": ^8.6.12
  "@storybook/test": ^8.6.14
  "@storybook/vue3": ^8.6.12
  "@storybook/vue3-vite": ^8.6.12
  "@storybook/web-components": 8.6.14
  "@storybook/web-components-vite": 8.6.14
  "@stylistic/eslint-plugin": ^5.4.0
  "@stylistic/eslint-plugin-js": ^4.2.0
  "@stylistic/eslint-plugin-ts": ^4.2.0
  "@stylistic/stylelint-plugin": ^3.1.3
  "@tsconfig/node24": ^24.0.3
  "@types/jsonwebtoken": ^9.0.9
  "@types/lodash-es": ^4.17.12
  "@types/node": ^24.10.1
  "@types/qs": ^6.9.18
  "@types/react": ^19.1.1
  "@types/react-dom": ^19.1.9
  "@typescript-eslint/eslint-plugin": ^8.29.1
  "@typescript-eslint/parser": ^8.29.1
  "@vite-pwa/vitepress": ^1.0.0
  "@vitejs/plugin-vue": ^6.0.2
  "@vitejs/plugin-vue-jsx": ^5.1.2
  "@vue/tsconfig": ^0.8.1
  antd: ^5.27.3
  axios: ^1.9.0
  axios-mock-adapter: ^2.1.0
  browserslist: ^4.24.4
  cac: ^6.7.14
  commitizen: ^4.3.1
  commitlint: ^19.8.0
  cspell: ^8.18.1
  cz-git: ^1.11.1
  defu: ^6.1.4
  depcheck: ^1.4.7
  echarts: ^5.6.0
  eslint: ^9.24.0
  eslint-import-resolver-typescript: ^4.3.2
  eslint-plugin-command: ^3.2.0
  eslint-plugin-eslint-comments: ^3.2.0
  eslint-plugin-import-x: ^4.10.2
  eslint-plugin-jsdoc: ^50.6.9
  eslint-plugin-jsonc: ^2.20.0
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-perfectionist: ^4.11.0
  eslint-plugin-prettier: ^5.2.6
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-compiler: 19.0.0-beta-e993439-20250405
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-regexp: ^2.7.0
  eslint-plugin-unicorn: ^58.0.0
  eslint-plugin-unused-imports: ^4.1.4
  eslint-plugin-vue: ^10.0.0
  execa: ^9.6.0
  find-up: ^8.0.0
  fork-ts-checker-webpack-plugin: ^9.0.3
  glob: ^11.0.3
  globals: ^16.0.0
  h3: ^1.15.3
  husky: ^9.1.7
  jsonc-eslint-parser: ^2.4.0
  jsonwebtoken: ^9.0.2
  lint-staged: ^15.5.0
  lit: ^3.3.1
  lodash-es: ^4.17.21
  markdownlint-cli2: ^0.17.2
  nitropack: ^2.11.12
  npm-package-json-lint: ^8.0.0
  npm-package-json-lint-config-default: ^7.0.1
  npm-run-all2: ^8.0.4
  only-allow: ^1.2.1
  pinia: ^3.0.4
  postcss-html: ^1.8.0
  prettier: ^3.5.3
  prettier-plugin-tailwindcss: ^0.6.14
  qs: ^6.14.0
  react: ^19.1.0
  react-dom: ^19.1.1
  react-router-dom: ^7.5.0
  resize-observer-polyfill: ^1.5.1
  rollup-plugin-postcss: ^4.0.2
  storybook: 8.6.14
  styled-components: ^6.1.19
  stylelint: ^16.17.0
  stylelint-config-recess-order: ^6.0.0
  stylelint-config-recommended: ^16.0.0
  stylelint-config-recommended-vue: ^1.6.0
  stylelint-config-standard: ^37.0.0
  stylelint-config-styled-components: ^0.1.1
  stylelint-order: ^6.0.4
  stylelint-prettier: ^5.0.3
  stylelint-processor-styled-components: ^1.10.0
  ts-loader: ^9.5.2
  typescript: ^5.8.3
  unbuild: ^3.5.0
  unfetch: ^4.2.0
  vite: ^7.2.4
  vite-plugin-dts: ^4.5.3
  vite-plugin-vue-devtools: ^8.0.5
  vitepress: ^1.6.3
  vitest: ^3.1.3
  vue: ^3.5.25
  vue-eslint-parser: ^10.1.3
  vue-router: ^4.6.3
  vue-tsc: ^3.1.5
  webpack: ^5.98.0
  webpack-cli: ^6.0.1
