packages:
  - packages*/**
catalog:
  "@changesets/cli": ^2.28.1
  "@commitlint/cli": ^19.8.0
  "@commitlint/config-conventional": ^19.8.0
  "@emotion/css": ^11.13.5
  "@eslint/js": ^9.24.0
  "@faker-js/faker": ^9.7.0
  "@storybook/addon-essentials": ^8.6.12
  "@storybook/addon-interactions": ^8.6.12
  "@storybook/addon-onboarding": ^8.6.12
  "@storybook/blocks": ^8.6.12
  "@storybook/react": ^8.6.12
  "@storybook/react-vite": ^8.6.12
  "@storybook/test": ^8.6.12
  "@storybook/vue3": ^8.6.12
  "@storybook/vue3-vite": ^8.6.12
  "@stylistic/eslint-plugin": ^4.2.0
  "@stylistic/eslint-plugin-js": ^4.2.0
  "@stylistic/eslint-plugin-ts": ^4.2.0
  "@types/jsonwebtoken": ^9.0.9
  "@types/lodash-es": ^4.17.12
  "@types/node": ^22.14.0
  "@types/qs": ^6.9.18
  "@types/react": ^19.1.1
  "@typescript-eslint/eslint-plugin": ^8.29.1
  "@typescript-eslint/parser": ^8.29.1
  "@vitejs/plugin-vue": ^5.2.3
  "@vitejs/plugin-vue-jsx": ^4.1.2
  axios: ^1.9.0
  axios-mock-adapter: ^2.1.0
  browserslist: ^4.24.4
  commitizen: ^4.3.1
  commitlint: ^19.8.0
  cspell: ^8.18.1
  cz-git: ^1.11.1
  defu: ^6.1.4
  depcheck: ^1.4.7
  echarts: ^5.6.0
  eslint: ^9.24.0
  eslint-import-resolver-typescript: ^4.3.2
  eslint-plugin-command: ^3.2.0
  eslint-plugin-eslint-comments: ^3.2.0
  eslint-plugin-import-x: ^4.10.2
  eslint-plugin-jsdoc: ^50.6.9
  eslint-plugin-jsonc: ^2.20.0
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-perfectionist: ^4.11.0
  eslint-plugin-prettier: ^5.2.6
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-compiler: 19.0.0-beta-e993439-20250405
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-regexp: ^2.7.0
  eslint-plugin-unicorn: ^58.0.0
  eslint-plugin-unused-imports: ^4.1.4
  eslint-plugin-vue: ^10.0.0
  fork-ts-checker-webpack-plugin: ^9.0.3
  globals: ^16.0.0
  h3: ^1.15.3
  husky: ^9.1.7
  jsonc-eslint-parser: ^2.4.0
  jsonwebtoken: ^9.0.2
  lint-staged: ^15.5.0
  lodash-es: ^4.17.21
  markdownlint-cli2: ^0.17.2
  nitropack: ^2.11.12
  npm-package-json-lint: ^8.0.0
  npm-package-json-lint-config-default: ^7.0.1
  only-allow: ^1.2.1
  postcss-html: ^1.8.0
  prettier: ^3.5.3
  qs: ^6.14.0
  react: ^19.1.0
  react-router-dom: ^7.5.0
  resize-observer-polyfill: ^1.5.1
  rollup-plugin-postcss: ^4.0.2
  storybook: ^8.6.12
  stylelint: ^16.17.0
  stylelint-config-recess-order: ^6.0.0
  stylelint-config-recommended: ^16.0.0
  stylelint-config-recommended-vue: ^1.6.0
  stylelint-config-standard: ^37.0.0
  stylelint-config-styled-components: ^0.1.1
  stylelint-order: ^6.0.4
  stylelint-prettier: ^5.0.3
  stylelint-processor-styled-components: ^1.10.0
  ts-loader: ^9.5.2
  typescript: ^5.8.3
  unbuild: ^3.5.0
  vite: ^6.2.6
  vite-plugin-dts: ^4.5.3
  vitepress: ^1.6.3
  vitest: ^3.1.3
  vue: ^3.5.13
  vue-eslint-parser: ^10.1.3
  vue-router: ^4.5.0
  vue-tsc: ^2.2.8
  webpack: ^5.98.0
  webpack-cli: ^6.0.1
