export { default as deviceOperatingSystem } from "./operating-system";
export { default as deviceBrowser } from "./browser";
export { default as deviceLanguage } from "./language";
export { default as deviceOnLine } from "./onLine";
export { default as deviceScreen } from "./screen";
export { default as deviceLocation } from "./location";
export { default as devicePublicIp } from "./public-ip";
export { default as deviceCpuCores } from "./cpu-cores";
export { default as deviceMemory } from "./memory";
