module.exports = [
    'content',
    'display',
    // grid
    'grid',
    'grid-auto-flow',
    'grid-auto-columns',
    'grid-auto-rows',
    'grid-gap',
    'grid-column-gap',
    'grid-row-gap',
    'grid-template',
    'grid-template-areas',
    'grid-template-columns',
    'grid-template-rows',
    // flex
    'flex',
    'flex-basis',
    'flex-direction',
    'flex-flow',
    'flex-grow',
    'flex-shrink',
    'flex-wrap',
    'align-content',
    'align-items',
    'align-self',
    'justify-content',
    'order',
    // position
    'position',
    'top',
    'right',
    'bottom',
    'left',
    // column
    'columns',
    'column-count',
    'column-width',
    'column-gap',
    'column-fill',
    'column-rule',
    'column-span',
    // floating
    'float',
    'clear',
    // can the box be seen?
    'visibility',
    'opacity',
    'z-index',
    // margin and padding
    'margin',
    'margin-top',
    'margin-right',
    'margin-bottom',
    'margin-left',
    'padding',
    'padding-top',
    'padding-right',
    'padding-bottom',
    'padding-left',
    // border
    'border',
    'border-top',
    'border-right',
    'border-bottom',
    'border-left',
    'border-width',
    'border-top-width',
    'border-right-width',
    'border-bottom-width',
    'border-left-width',
    'border-style',
    'border-top-style',
    'border-right-style',
    'border-bottom-style',
    'border-left-style',
    'border-color',
    'border-top-color',
    'border-right-color',
    'border-bottom-color',
    'border-left-color',
    'border-radius',
    'border-top-left-radius',
    'border-top-right-radius',
    'border-bottom-left-radius',
    'border-bottom-right-radius',
    'border-collapse', // just for table
    'border-spacing', // just for table
    'box-shadow',
    'box-sizing',
    'outline',
    // Content dimensions and background and scrollbars
    'background',
    'background-clip',
    'background-color',
    'background-image',
    'background-position',
    'background-repeat',
    'background-size',
    // size
    'width',
    'min-width',
    'max-width',
    'height',
    'min-height',
    'max-height',
    'line-height', // for text
    // overflow
    'overflow',
    'overflow-x',
    'overflow-y',
    // cursor
    'cursor',
    // special content types: lists, tables
    'list-style',
    'caption-side',
    'table-layout',
    'empty-cells',
    // textual content
    'font',
    'font-family',
    'font-size',
    'font-weight',
    'font-style',
    'font-variant',
    'font-smoothing',
    'vertical-align',
    'text-align',
    'text-decoration',
    'text-indent',
    'text-overflow',
    'text-rendering',
    'text-shadow',
    'text-transform',
    'letter-spacing',
    'word-spacing',
    'white-space',
    'word-wrap',
    'word-break',
    'color',
    'quotes',
    // transform
    'transform',
    'transform-origin',
    // transitions change previously defined properties
    'transition',
    'transition-property',
    'transition-duration',
    'transition-timing-function',
    'transition-delay'
]