#!/usr/bin/env sh

check_branch() {
  branch="$(git rev-parse --abbrev-ref HEAD)"
  
  if [ "$branch" = "master" ] || [ "$branch" = "main" ]; 
    then
      echo "❌ Do NOT commit on \"$branch\""
      exit 1
    fi
}

check_branch

# npx lint-staged
# 提交时运行的指令