#!/usr/bin/env sh

# 检查 Git 用户信息，保证用户名统一为小写的 `名.姓`，并仅允许公司邮箱
check_user() {
  # userName="$(git config user.name)" # Git 要求一定有 user.name，这里一定有值
  
  # if [[ ! "$userName" =~ ^[a-z]+\.[a-z]+$ ]]; then
  #   echo "Git user.name \"$userName\" not in \"name.surname\" format"
  #   exit 1
  # fi
  
  userEmail="$(git config user.email)"
  
  if [ -z "$userEmail" ] || [[ ! "$userEmail" =~ @\w+\.com$ ]] && [[ ! "$userEmail" =~ @163\.com$ ]] && [[ ! "$userEmail" =~ @qq\.com$ ]]; then
    echo "Git user.email not a company email"
    exit 1
  fi
}

# 不允许直接在主分支上提交代码
check_branch() {
  branch="$(git rev-parse --abbrev-ref HEAD)"
  
  if [ "$branch" = "master" ] || [ "$branch" = "main" ]; then
    echo "Do NOT commit on \"$branch\""
    exit 1
  fi
}

check_user
check_branch

echo "Running lint-staged..."

npx lint-staged
